server:
  port: 8081
spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchenge:
        producer: ex.producer.ubs
      routing-key:
        producer: rk.producer.ubs
      dead-letter:
        producer: dl.producer.ubs
      parking-lot:
        producer: pl.producer.ubs